### ISSUE TITLE
Rolle wird nur für Montag ausgefüllt

### ISSUE THREAD

**Issue by smotastic** [kokolorika/timesheet#20]
Die in den Settings eingegeben Rolle wird nur im Kommentar angezeigt, wenn für Montag Zeiten eingegeben wurden. 
Wenn Montags bspw. Feiertag ist und die Woche erst Dienstags beginnt, sollte die Rolle im Kommentar beim Dienstag stehen.

**Comment by thomasbreitbach** [comment]
Aktuell gibt es vom Pmo nur die Vorgabe, dass die Rolle für Montag angegeben werden muss.

**Comment by thomasbreitbach** [comment]
Die Rolle ist seit 22.08.19 nicht mehr notwendig
