### ISSUE TITLE
Default-Transportmittel in der Analyse funktioniert nicht

### ISSUE THREAD

**Issue by Steph0r** [kokolorika/timesheet#48]
Mit den Echtdaten funktioniert das Feature #47 bei mir nicht, obwohl ich mir relativ sicher bin, dass es beim Review lokal ging.
Hier bei der Prüfung, ob tmpTransport gefüllt ist geht er nicht rein. 
https://github.com/kokolorika/timesheet/blob/39dbb0afb54675af94525e6d67ada86166c6b892/js/expenses.js#L9
Laut debugger ist `tmpTransport` nicht leer, sondern `undefined`.
Als fix würde ich vorschlagen, statt `tmpTransport == ''` `!tmpTransport`
 zu prüfen. Ich glaube jedenfalls, dass sowohl `undefined` als auch ein leerer String in js falsey sind (klar)

**Comment by thomasbreitbach** [comment]
Wird hier auch so vorgeschlagen: https://stackoverflow.com/a/154068

> If you just want to check whether there's any value, you can do
if (strValue) {
    //do something
}
